# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd7190a2c91d2133b64b42fd6af1f1f393b4e0ee99da611f3e797a8bf61c16b7ce0705bf7411f6e9b9645e84da3a8fab23689d3c7773635667a1cb7abffb39af

test:
  secret_key_base: 669049af1d128156b5dbcc06c2d4516df4867bdca5e37e11de0ff613d2cd6d75d378f31e8d3325e8bf5c765a4290915aa0695abf48bf62ace57c75e03f02cf84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
